FROM 773153459320.dkr.ecr.eu-west-1.amazonaws.com/angus.box/genericservice

#
# Service
#
COPY angus /angus

#
# Entrypoint
#
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

# Python
RUN   apt-get update && apt-get install -y \
      python-dev \
# Clean
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*


RUN pip install pyinstaller

RUN mkdir -p /angus/services/angus/
RUN cp /usr/local/lib/python2.7/dist-packages/angus/*.py /angus/.

RUN pyinstaller --onefile angus/services/gateway.py
